/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.icube;
//import GreetServer.java;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Timestamp;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author user
 */
public class homeFormUI extends javax.swing.JFrame {

    /**
     * Creates new form homeFormUI
     */
    Timestamp timestamp = new Timestamp(System.currentTimeMillis());
    public homeFormUI() {
        
        initComponents();
        
        this.setLocationRelativeTo(null); //set the location for the popup in the middle of the screen

        ImageIcon faceImage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/face.png")));
        ImageIcon ppeImage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/PPE_detection.png")));
        ImageIcon objectImage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/objectdetection.png")));
        ImageIcon countImage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/peoplecounting.png")));
        ImageIcon colorImage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/color.png")));
        ImageIcon motionImage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/motion.jpg")));
        
        
        //face Icon
        Image img1 = faceImage.getImage();
        Image img2 = img1.getScaledInstance(jLabelFaceIcon.getWidth(), jLabelFaceIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        jLabelFaceIcon.setIcon(i);
//        jLabelFaceIndividual.setIcon(i);
       
        //ppe icon
        Image imgPPE = ppeImage.getImage();
        Image imgPPE2 = imgPPE.getScaledInstance(jLabelPPEIcon.getWidth(), jLabelPPEIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ppe = new ImageIcon(imgPPE2);
        jLabelPPEIcon.setIcon(ppe);
        
        //object detection jLabelObjectIcon
        Image imgObject = objectImage.getImage();
        Image imgObject2 = imgObject.getScaledInstance(jLabelObjectIcon.getWidth(), jLabelObjectIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon object = new ImageIcon(imgObject2);
        jLabelObjectIcon.setIcon(object);
        
        //people counting jLabelPeopleCountIcon
        Image imgCount = countImage.getImage();
        Image imgCount2 = imgCount.getScaledInstance(jLabelPeopleCountIcon.getWidth(), jLabelPeopleCountIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon count = new ImageIcon(imgCount2);
        jLabelPeopleCountIcon.setIcon(count);
        
        //color jLabelColorIcon
        Image imgColor = colorImage.getImage();
        Image imgColor2 = imgColor.getScaledInstance(jLabelColorIcon.getWidth(), jLabelColorIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon color = new ImageIcon(imgColor2);
        jLabelColorIcon.setIcon(color);
        
        //motion jLabelMotionIcon
        Image imgMotion = motionImage.getImage();
        Image imgMotion2 = imgMotion.getScaledInstance(jLabelMotionIcon.getWidth(), jLabelMotionIcon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon motion = new ImageIcon(imgMotion2);
        jLabelMotionIcon.setIcon(motion);
       
//        jTextArea1.append("");
        jTextArea1.setText(null);
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelHome = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelCurrentRunning = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelFaceIcon = new javax.swing.JLabel();
        jLabelMotionIcon = new javax.swing.JLabel();
        jLabelPeopleCountIcon = new javax.swing.JLabel();
        jLabelObjectIcon = new javax.swing.JLabel();
        jLabelPPEIcon = new javax.swing.JLabel();
        jLabelColorIcon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonClear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 37, 42));

        jLabelHome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelHome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iCube.png"))); // NOI18N
        jLabelHome.setText("HOME");
        jLabelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseClicked(evt);
            }
        });

        jLabelExit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelExit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExit.setText("X");
        jLabelExit.setToolTipText("Exit Application");
        jLabelExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelExitMouseExited(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(36, 37, 42));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Settings");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Preference");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setVisible(false);
        jLabel9.setEnabled(false);
        jLabel10.setVisible(false);
        jLabel10.setEnabled(false);

        jLabelCurrentRunning.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCurrentRunning.setText("Currently running : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabelHome)
                .addGap(66, 66, 66)
                .addComponent(jLabelCurrentRunning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 421, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabelExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCurrentRunning)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelHome, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        jLabelExit.setEnabled(false);

        jPanel2.setBackground(new java.awt.Color(218, 223, 225));

        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabelFaceIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFaceIcon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelFaceIcon.setOpaque(true);
        jLabelFaceIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFaceIconMouseClicked(evt);
            }
        });

        jLabelMotionIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMotionIcon.setAlignmentY(0.0F);
        jLabelMotionIcon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelMotionIcon.setOpaque(true);
        jLabelMotionIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMotionIconMouseClicked(evt);
            }
        });

        jLabelPeopleCountIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPeopleCountIcon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelPeopleCountIcon.setOpaque(true);
        jLabelPeopleCountIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPeopleCountIconMouseClicked(evt);
            }
        });

        jLabelObjectIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelObjectIcon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelObjectIcon.setOpaque(true);
        jLabelObjectIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelObjectIconMouseClicked(evt);
            }
        });

        jLabelPPEIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPPEIcon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelPPEIcon.setOpaque(true);
        jLabelPPEIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPPEIconMouseClicked(evt);
            }
        });

        jLabelColorIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelColorIcon.setToolTipText("");
        jLabelColorIcon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelColorIcon.setMaximumSize(new java.awt.Dimension(20, 20));
        jLabelColorIcon.setMinimumSize(new java.awt.Dimension(20, 20));
        jLabelColorIcon.setOpaque(true);
        jLabelColorIcon.setPreferredSize(new java.awt.Dimension(20, 20));
        jLabelColorIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelColorIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPeopleCountIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFaceIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelPPEIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelObjectIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelColorIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jLabelMotionIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFaceIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPPEIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelObjectIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPeopleCountIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelColorIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMotionIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(189, 195, 199));
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonClear.setBackground(new java.awt.Color(255, 102, 102));
        jButtonClear.setText("Clear");
        jButtonClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClearMouseClicked(evt);
            }
        });
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jLabel2.setText("Operation   |    Time");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonClear)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(70, 70, 70))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClear)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new loginFormUI().setVisible(true);
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel3MouseExited

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add your handling code here:
        jLabel9.setVisible(rootPaneCheckingEnabled);
        jLabel10.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        // TODO add your handling code here:
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
    }//GEN-LAST:event_jPanel4MouseExited

    private void jLabelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseEntered
        // TODO add your handling code here:
        jLabelExit.setEnabled(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jLabelExitMouseEntered

    private void jLabelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseExited
        // TODO add your handling code here:
        jLabelExit.setEnabled(false);
    }//GEN-LAST:event_jLabelExitMouseExited

    private void jButtonClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClearMouseClicked
        // TODO add your handling code here:
        jTextArea1.setText(null);
    }//GEN-LAST:event_jButtonClearMouseClicked

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jLabelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseClicked
        // TODO add your handling code here:
//        jPanel3.setVisible(false);
        this.dispose();
        new homeFormUI().setVisible(true);
    }//GEN-LAST:event_jLabelHomeMouseClicked

    private void jLabelColorIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelColorIconMouseClicked
        // TODO add your handling code here:
        //        System.out.println("Color Pressed");
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        jTextArea1.append("Color Pressed | " + timestamp + "\n");
    }//GEN-LAST:event_jLabelColorIconMouseClicked

    private void jLabelPPEIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPPEIconMouseClicked
        // TODO add your handling code here:
        //        System.out.println("PPE Detection Pressed");
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        jTextArea1.append("PPE Detection | " + timestamp + "\n");
    }//GEN-LAST:event_jLabelPPEIconMouseClicked

    private void jLabelObjectIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelObjectIconMouseClicked
        // TODO add your handling code here:
        //        System.out.println("Object Detection Pressed");
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        jTextArea1.append("Object Detection | " + timestamp + "\n");
    }//GEN-LAST:event_jLabelObjectIconMouseClicked

    private void jLabelPeopleCountIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPeopleCountIconMouseClicked
        // TODO add your handling code here:
        //        System.out.println("People Counting Pressed");
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        jTextArea1.append("People Counting | " + timestamp + "\n");
    }//GEN-LAST:event_jLabelPeopleCountIconMouseClicked

    private void jLabelMotionIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMotionIconMouseClicked
        // TODO add your handling code here:
        //        System.out.println("Motion Pressed");
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        jTextArea1.append("Motion Pressed | " + timestamp + "\n");
    }//GEN-LAST:event_jLabelMotionIconMouseClicked

    private void jLabelFaceIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFaceIconMouseClicked
        // TODO add your handling code here:
        //        System.out.println("Face Recognition Pressed");
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        jTextArea1.append("Face Recognition | " + timestamp + "\n");
//        jPanel3.setEnabled(true);
//        jPanel5.setVisible(true);
    }//GEN-LAST:event_jLabelFaceIconMouseClicked

    private void jLabelFaceIcon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFaceIcon1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFaceIcon1MouseClicked

    private void jLabelMotionIcon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMotionIcon1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMotionIcon1MouseClicked

    private void jLabelPeopleCountIcon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPeopleCountIcon1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelPeopleCountIcon1MouseClicked

    private void jLabelObjectIcon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelObjectIcon1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelObjectIcon1MouseClicked

    private void jLabelPPEIcon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPPEIcon1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelPPEIcon1MouseClicked

    private void jLabelColorIcon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelColorIcon1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelColorIcon1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeFormUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeFormUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeFormUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeFormUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new homeFormUI().setVisible(true);
                    }
                });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelColorIcon;
    private javax.swing.JLabel jLabelCurrentRunning;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelFaceIcon;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelMotionIcon;
    private javax.swing.JLabel jLabelObjectIcon;
    private javax.swing.JLabel jLabelPPEIcon;
    private javax.swing.JLabel jLabelPeopleCountIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
